h_thon/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls.static import static
# from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('savior.urls')),
]

# urlpatterns += \
#     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

savior/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name='savior'

urlpatterns = [
    path('', views.main , name='main'),
    path('pricelist/', views.pricelist , name='pricelist'),
    path('exchange/', views.exchange , name='exchange'),
    path('recommend/', views.recommend , name='recommend'),
    path('map/', views.map , name='map'),
    path('intro/', views.intro , name='intro'),

    #일본
    path('japan/', views.japan , name='japan'),
    path('japan_exchange/', views.japan_exchange , name='japan_exchange'),
    path('japan_pricelist/', views.japan_pricelist , name='japan_pricelist'),
    path('japan_clothes/', views.japan_clothes , name='japan_clothes'),
    path('japan_clothes_detail/<int:id>', views.japan_clothes_detail , name='japan_clothes_detail'),
    path('japan_foods/', views.japan_foods , name='japan_foods'),
    path('japan_foods_detail/<int:id>', views.japan_foods_detail , name='japan_foods_detail'),
    path('japan_others/', views.japan_others , name='japan_others'),
    path('japan_others_detail/<int:id>', views.japan_others_detail , name='japan_others_detail'),
    
    #미국
    path('USA/', views.usa , name='USA'),
    path('USA_exchange/', views.usa_exchange , name='USA_exchange'),
    path('USA_pricelist/', views.usa_pricelist , name='USA_pricelist'),
    path('USA_clothes/', views.usa_clothes , name='USA_clothes'),
    path('USA_clothes_detail/<int:id>', views.usa_clothes_detail , name='USA_clothes_detail'),
    path('USA_foods/', views.usa_foods , name='USA_foods'),
    path('USA_foods_detail/<int:id>', views.usa_foods_detail , name='USA_foods_detail'),
    path('USA_others/', views.usa_others , name='USA_others'),
    path('USA_others_detail/<int:id>', views.usa_others_detail , name='USA_others_detail'),

    #베트남
    path('vietnam/', views.vietnam , name='vietnam'),
    path('vietnam_exchange/', views.vietnam_exchange , name='vietnam_exchange'),
    path('vietnam_pricelist/', views.vietnam_pricelist , name='vietnam_pricelist'),
    path('vietnam_clothes/', views.vietnam_clothes , name='vietnam_clothes'),
    path('vietnam_clothes_detail/<int:id>', views.vietnam_clothes_detail , name='vietnam_clothes_detail'),
    path('vietnam_foods/', views.vietnam_foods , name='vietnam_foods'),
    path('vietnam_foods_detail/<int:id>', views.vietnam_foods_detail , name='vietnam_foods_detail'),
    path('vietnam_others/', views.vietnam_others , name='vietnam_others'),
    path('vietnam_others_detail/<int:id>', views.vietnam_others_detail , name='vietnam_others_detail'),
    
    #* 로그인 및 회원가입
    path('accounts/', include('accounts.urls', namespace='accounts' )),

    #* 마이페이지 
    path('mypage/', views.mypage, name='mypage'),
    
    #* 카카오 로그인
    path('users/', include('users.urls', namespace='users')),

    #커뮤니티
    path('community/', views.community, name='community'),
    path('community_post/', views.community_post, name='community_post'),
    path('community_tag/<str:tag_name>', views.community_tag, name='community_tag'),
    path('community_tag/일본', views.community_tag_japan, name='community_tag_japan'),
    path('community_tag/미국', views.community_tag_USA, name='community_tag_USA'),
    path('community_tag/베트남', views.community_tag_vietnam, name='community_tag_vietnam'),
    path('<int:id>/likes/', views.likes, name='likes'),
    path('community_detail/<int:id>', views.community_detail, name='community_detail'),
    path('community_delete/<int:id>', views.community_delete, name='community_delete'),

    #* 식당 추천 
    path('recommend_USA/', views.recommend_restaurant, name='recommend_USA'),
    path('recommend_japan/', views.Japan_restaurant, name='recommend_japan'),
    path('recommend_vietnam/', views.Vietnam_restaurant, name='recommend_vietnam'),


]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

users/urls.py
from django.urls import path
from . import views
from .views import kakao_login, kakao_login_callback

app_name = "users"


urlpatterns = [
    
    # 카카오 로그인 
    path("login/kakao/", views.kakao_login, name="kakao_login"),
    path(
        "login/kakao/callback/",
        views.kakao_login_callback,
        name="kakao-callback",
    ),
    
]

savior/models.py
from django.db import models
from users.models import *
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.

#일본
class Japan_clothes(models.Model):  
    japan_clothes = models.CharField(max_length=10)

    def __str__(self):
        return self.japan_clothes

#* 시세 입력 페이지
class Japan_clothes_Comment(models.Model):  
    user = models.ForeignKey(
        "users.User",
        verbose_name="일본 의류 시세 댓글 작성자",
        on_delete=models.CASCADE,
    )
    japan_clothes_post = models.ForeignKey(Japan_clothes, verbose_name="일본 의류 시세 댓글", on_delete=models.CASCADE)
    content = models.TextField("내용")
    number = models.IntegerField("숫자") #! 금액 입력 창 
    created = models.DateTimeField(auto_now_add=True)

class Japan_foods(models.Model):
    japan_foods = models.CharField(max_length=10)

    def __str__(self):
        return self.japan_foods
    
class Japan_others(models.Model):
    japan_others = models.CharField(max_length=10)

    def __str__(self):
        return self.japan_others
    
class Japan_others_Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="일본 잡화 시세 댓글 작성자",
        on_delete=models.CASCADE,
    )
    japan_others_post = models.ForeignKey(Japan_others, verbose_name="일본 잡화 시세 댓글", on_delete=models.CASCADE)
    content = models.TextField("내용")
    number = models.IntegerField("숫자")
    created = models.DateTimeField(auto_now_add=True)

#미국
class USA_clothes(models.Model):
    usa_clothes = models.CharField(max_length=10)

    def __str__(self):
        return self.usa_clothes
    
class USA_clothes_Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="미국 의류 시세 댓글 작성자",
        on_delete=models.CASCADE,
    )
    usa_clothes_post = models.ForeignKey(USA_clothes, verbose_name="미국 의류 시세 댓글", on_delete=models.CASCADE)
    content = models.TextField("내용")
    number = models.IntegerField("숫자")
    created = models.DateTimeField(auto_now_add=True)

class USA_foods(models.Model):
    usa_foods = models.CharField(max_length=10)

    def __str__(self):
        return self.usa_foods
    
class USA_others(models.Model):
    usa_others = models.CharField(max_length=10)

    def __str__(self):
        return self.usa_others
    
    
    #* 미국 잡화 시세 입력 페이지
class USA_others_Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="미국 잡화 시세 댓글 작성자",
        on_delete=models.CASCADE,
    )
    usa_others_post = models.ForeignKey(USA_others, verbose_name="미국 잡화 시세 댓글", on_delete=models.CASCADE)
    content = models.TextField("내용")
    number = models.IntegerField("숫자")
    created = models.DateTimeField(auto_now_add=True)
    
#베트남
class Vietnam_clothes(models.Model):
    vietnam_clothes = models.CharField(max_length=10)

    def __str__(self):
        return self.vietnam_clothes
    
    #* 시세 입력 페이지
class Vietnam_clothes_Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="베트남 의류 시세 댓글 작성자",
        on_delete=models.CASCADE,
    )
    vietnam_clothes_post = models.ForeignKey(Vietnam_clothes, verbose_name="베트남 의류 시세 댓글", on_delete=models.CASCADE)
    content = models.TextField("내용")
    number = models.IntegerField("숫자")
    created = models.DateTimeField(auto_now_add=True)

class Vietnam_foods(models.Model):
    vietnam_foods = models.CharField(max_length=10)

    def __str__(self):
        return self.vietnam_foods
    
class Vietnam_others(models.Model):
    vietnam_others = models.CharField(max_length=10)

    def __str__(self):
        return self.vietnam_others
    
class Vietnam_others_Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="베트남 잡화 시세 댓글 작성자",
        on_delete=models.CASCADE,
    )
    vietnam_others_post = models.ForeignKey(Vietnam_others, verbose_name="베트남 잡화 시세 댓글", on_delete=models.CASCADE)
    content = models.TextField("내용")
    number = models.IntegerField("숫자")
    created = models.DateTimeField(auto_now_add=True)


#커뮤니티 기능
class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    title = models.CharField("제목", max_length=30, default='')
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)
    thumbnail = models.ImageField("썸네일 이미지", upload_to="post", blank=True)
    tags = models.ManyToManyField('HashTag', verbose_name='해시태그 목록', blank=True)

class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")

class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length=20)

    def __str__(self):
        return self.name
    

savior/templates/community.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Savior : 자유게시판</title>
    <link rel="stylesheet" href="{% static 'css/community.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Judson&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="container">
      <div class="background"></div>
      <header class="hd">
        <div class="hd-back">
          <img
            src="{% static 'image/nav/back.svg' %}"
            style="height: 30px"
            onclick="goBack()"
          />
        </div>
        <div class="hd-logo">
          <img src="{% static 'image/savior.png' %}" />
        </div>
        <div class="hd-profile">
          <a href=""> <img src="{% static 'image/nav/user_color.png' %}" /></a>
        </div>
      </header>

      <div class="inform">
        <div class="title">
          <p>자유게시판</p>
        </div>
      </div>

      <section class="sec">
        <div class="choice">
          <div class="country">
            <span
              ><a href="{% url 'savior:community_tag_japan' %}">#일본</a></span
            >
          </div>
          <div class="country">
            <span
              ><a href="{% url 'savior:community_tag_USA' %}">#미국</a></span
            >
          </div>
          <div class="country">
            <span
              ><a href="{% url 'savior:community_tag_vietnam' %}"
                >#베트남</a
              ></span
            >
          </div>
        </div>

        {% for post in posts %}
        <div class="list">
          <div class="box">
            <div class="picbox">
              {% if post.thumbnail %}
              <img src="{{post.thumbnail.url}}" alt="" />
              {% endif %}
            </div>
            <div class="writebox">
              <p>
                <a href="{% url 'savior:community_detail' post.pk %}"
                  >{{post.title}}</a
                >
              </p>
              <div class="list_user">
                <div class="heart">
                  <img src="{% static 'image/icon/heart-outline.svg' %}" />
                  <span>{{ post.like_users.count }}</span>
                </div>
                <span>{{ post.user.username }}</span>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        <div class="btn_write">
          <a href="{% url 'savior:community_post' %}"
            ><button type="button" onclick="" id="btn">글쓰기</button></a
          >
        </div>
      </section>

      <navigation class="nav">
        <a href="{% url 'savior:exchange' %}"
          ><img src="{% static 'image/nav/money.svg' %}"
        /></a>
        <a href="{% url 'savior:recommend' %}"
          ><img src="{% static 'image/nav/eat.png' %}"
        /></a>
        <a href="{% url 'savior:map' %}"
          ><img
            src="{% static 'image/nav/pin_color.png' %}"
            style="height: 45px"
        /></a>
        <a href="{% url 'savior:pricelist' %}"
          ><img src="{% static 'image/nav/tag_color.png' %}"
        /></a>
        <a href="{% url 'savior:community' %}"
          ><img src="{% static 'image/nav/edit-message.png' %}"
        /></a>
      </navigation>
    </div>
    <script src="{% static 'js/go-back.js' %}"></script>
    <script src="{% static 'js/go-back-nonclick.js' %}"></script>
  </body>
</html>

savior/templates/community_post.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Savior : 게시글 작성</title>
    
    <link rel="stylesheet" href="{% static 'css/community_post.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Judson&display=swap" rel="stylesheet"/>
    <body>
        <div class="container">
            <div class="background"></div>
            <header class="hd">
                <div class="hd-back">
                    <img
                        src="{% static 'image/nav/back.svg' %}"
                        style="height: 30px"
                        onclick="goBack()"
                    />
                </div>
                <div class="hd-logo">
                    <img src="{% static 'image/savior.png' %}"/>
                </div>
                <div class="hd-profile">
                    <a href="{% url 'savior:mypage' %}"> <img src="{% static 'image/nav/user_color.png' %}"/></a>
                </div>
            </header>

            <div class="inform">
                <div class="title">
                    <p>새 글 작성</p>
                </div>
            </div>

            <section class="sec">
                <form action="{% url 'savior:community_post' %}" method="POST" class="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="text" id="page-title" name="title" placeholder="글 제목을 입력해주세요">
                    <input id="country-tags" name="tags" type="text" placeholder=" 국가 태그를 입력해주세요 (ex. 일본 / 일본,미국)">
                    <hr>
                    <textarea name="content" id="page-textarea" cols="30" rows="13" placeholder="글 내용을 입력해주세요"></textarea>
                    <div class="filebox">
                        <label for="file">
                            <div class="file-upload">첨부 파일 </div>
                        </label>
                        <input type="file" name="thumbnail" id="file" accept="image">
                        <!-- <span> | </span> -->
                        <!-- <button id="cancelButton">취소</button> -->
                    </div>
                    <div class="submit"">
                        <input type="submit" class="submit-button" >
                    </div>
                </form>
            </section>

            <navigation class="nav">
                <a href="{% url 'savior:exchange' %}"><img src="{% static 'image/nav/money.svg' %}" /></a>
                <a href="{% url 'savior:recommend' %}"><img src="{% static 'image/nav/eat.png' %}" /></a>
                <a href="{% url 'savior:map' %}"><img src="{% static 'image/nav/pin_color.png' %}" style="height: 45px"/></a>
                <a href="{% url 'savior:pricelist' %}"><img src="{% static 'image/nav/tag_color.png' %}" /></a>
                <a href="{% url 'savior:community' %}"><img src="{% static 'image/nav/edit-message.png' %}" /></a>
            </navigation>
        </div>
        <script src="{% static 'js/go-back.js' %}"></script>
        <script src="{% static 'js/go-back-nonclick.js' %}"></script>
        <script src="{% static 'js/scrap.js' %}"></script>
        <script src="{% static 'js/community_post.js' %}"></script>
    </body>
</html>

savior/templates/community_tag.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Savior : 자유게시판</title>
        <link rel="stylesheet" href="{% static 'css/community.css' %}" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Judson&display=swap"
            rel="stylesheet"
        />
    </head>
    <body>
        <div class="container">
            <div class="background"></div>
            <header class="hd">
                <div class="hd-back">
                    <img
                        src="{% static 'image/nav/back.svg' %}"
                        style="height: 30px"
                        onclick="goBack()"
                    />
                </div>
                <div class="hd-logo">
                    <img src="{% static 'image/savior.png' %}" />
                </div>
                <div class="hd-profile">
                    <a href="">
                        <img src="{% static 'image/nav/user_color.png' %}"
                    /></a>
                </div>
            </header>

            <div class="inform">
                <div class="title">
                    <p>자유게시판</p>
                </div>
            </div>

            <section class="sec">
                <div class="choice">
                    <div class="country">
                        <span>#{{ tag_name }}</span>
                    </div>
                    <div class="country">
                        <span>게시물 수: {{ posts.count }}</span>
                    </div>
                </div>

                {% for post in posts %}
                <div class="list">
                    <div class="box">
                        <div class="picbox">
                            {% if post.thumbnail %}
                            <img src="{{post.thumbnail.url}}" alt="" />
                            {% endif %}
                        </div>
                        <div class="writebox">
                            <p>
                                <a
                                    href="{% url 'savior:community_detail' post.pk %}"
                                    >{{post.title}}</a
                                >
                            </p>
                            <div class="list_user">
                                <div class="heart">
                                    <img
                                        src="{% static 'image/icon/heart-outline.svg' %}"
                                    />
                                    <span>{{ post.like_users.count }}</span>
                                </div>
                                <span>{{ post.user.username }}</span>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <!-- <div class="btn_write">
                <a href="{% url 'savior:community_post' %}"><button type="button" onclick="" id="btn">글쓰기</button></a>
            </div> -->
            </section>

            <navigation class="nav">
                <a href="{% url 'savior:exchange' %}"
                    ><img src="{% static 'image/nav/money.svg' %}"
                /></a>
                <a href="{% url 'savior:recommend' %}"
                    ><img src="{% static 'image/nav/eat.png' %}"
                /></a>
                <a href="{% url 'savior:map' %}"
                    ><img
                        src="{% static 'image/nav/pin_color.png' %}"
                        style="height: 45px"
                /></a>
                <a href="{% url 'savior:pricelist' %}"
                    ><img src="{% static 'image/nav/tag_color.png' %}"
                /></a>
                <a href="{% url 'savior:community' %}"
                    ><img src="{% static 'image/nav/edit-message.png' %}"
                /></a>
            </navigation>
        </div>
        <script src="{% static 'js/go-back.js' %}"></script>
        <script src="{% static 'js/go-back-nonclick.js' %}"></script>
    </body>
</html>

savior/templates/mypage.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Savoir : mypage</title>
    <link rel="stylesheet" href="{% static 'css/mypage.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Judson&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
  </head>
  <body>
    {% block content %}
    <!-- <a href="{% url 'savior:main' %}">뒤로가기</a><br />
        <a href="{% url 'savior:mypage' %}">마이페이지</a><br /><br /> -->

    <div class="container">
      <div class="background"></div>
      <header class="hd">
        <div class="hd-back">
          <img src="{% static 'image/nav/back.svg' %}" style="height: 30px" onclick="goBack()" />
        </div>
        <div class="hd-logo">
          <img src="{% static 'image/savior.png' %}./" />
        </div>
        <div class="hd-profile">
          <a href=""> <img src="{% static 'image/nav/user_color.png' %}" /></a>
        </div>
      </header>

      <div class="inform">
        <div class="title">
          <p>MyPage</p>
        </div>
      </div>

      <section class="sec">
        <div id="mention">
          <!--! 로그인, 회원가입, 로그아웃 -->
          <!--* 로그인 사용자 이름(id) 확인 -->
          {% if request.user.is_authenticated %}
          <h3>{{ request.user.username }}님, 반갑습니다</h3>
        </div>

        <!-- 스크랩한 국가 목록 -->
        <div id="contries-area" class="area-box">
          <h4 class="titles">Countries<img src="{% static 'image/icon/bookmark.png' %}" class="title-icon" /></h4>
          <hr />

          <div class="swiper-container">
            <!-- If we need navigation buttons -->
            <div
              class="swiper-button-prev"
              style="
                position: relative;
                top: 100px;

                color: #000;
              "
            ></div>
            <div
              class="swiper-button-next"
              style="
                position: relative;
                top: 80px;
                left: 280px;

                color: #000;
              "
            ></div>
            <div class="swiper-wrapper">
              <div class="swiper-slide">
                <a href="{% url 'savior:USA' %}"> <img src="{% static 'image/flag/USA.png' %}" alt="usa" /><br />미국</a>
              </div>
              <div class="swiper-slide">
                <a href="{% url 'savior:japan' %}"> <img src="{% static 'image/flag/Japan.png' %}" alt="japan" /><br />일본</a>
              </div>
              <div class="swiper-slide">
                <a href="{% url 'savior:vietnam' %}"> <img src="{% static 'image/flag/Vietnam.png' %}" alt="vietnam" /><br />베트남</a>
              </div>
            </div>
            <!-- If we need pagination -->
            <div class="swiper-pagination" style="position: static"></div>
          </div>
        </div>

        <!-- 내가 쓴 글 목록 -->
        <div id="posts-area" class="area-box">
          <h4 class="titles">Posts<img src="{% static 'image/icon/post.svg' %}" class="title-icon" /></h4>
          <hr />

          {% for post in request.user.post_set.all %}
          <a href="{% url 'savior:community_detail' post.id %}"
            ><div class="post-box">
              <div class="post-info-top">
                <p>{{ post.user }}</p>
                <p>{{ post.created|date:"Y년 m월 d일 H:i" }}</p>
              </div>
              <div class="post-info-main">
                <p id="post-title">{{ post.title }}</p>
              </div>
            </div>
          </a>
          {% endfor %}
        </div>

        <!-- 내가 쓴 댓글 목록 -->
        <div id="comments-area" class="area-box">
          <h4 class="titles">Comments<img src="{% static 'image/icon/comment.svg' %}" class="title-icon" /></h4>
          <hr />

          {% for comment in request.user.comment_set.all %}
          <a href="{% url 'savior:community_detail' comment.post.id %}">
            <div class="comment-box">
              <div class="comment-info-top">
                <p>{{ comment.user }}</p>
                <p>{{comment.created|date:"Y년 m월 d일 H:i" }}</p>
              </div>
              <div class="comment-info-main">
                <p id="comment-title">{{ comment.content }}</p>
              </div>
            </div>
          </a>
          {% endfor %}
          <br />
          {% else %}
          <span>먼저 로그인 해주세요 </span><br />

          <!--* 로그아웃 버튼 -->
          <button id="login_btn">
            <a href="{% url 'savior:accounts:login' %}" style="color: #fff">로그인</a>
          </button>
          {% endif %}
          <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
          <script src="./js/mypage.js"></script>
          <script src="./js/go-back.js"></script>
          <script src="./js/go-back-nonclick.js"></script>
        </div>
      </section>
      <navigation class="nav">
        <a href="{% url 'savior:exchange' %}"><img src="{% static 'image/nav/money.svg' %}" /></a>
        <a href="{% url 'savior:recommend' %}"><img src="{% static 'image/nav/eat.png' %}" /></a>
        <a href="{% url 'savior:map' %}"><img src="{% static 'image/nav/pin_color.png' %}" style="height: 45px" /></a>
        <a href="{% url 'savior:pricelist' %}"><img src="{% static 'image/nav/tag_color.png' %}" /></a>
        <a href="{% url 'savior:community' %}"><img src="{% static 'image/nav/edit-message.png' %}" /></a>
      </navigation>
    </div>

    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="{% static 'js/mypage.js' %}"></script>
    <script src="{% static 'js/go-back.js' %}"></script>
    <script src="{% static 'js/go-back-nonclick.js' %}"></script>
    {% endblock %}
  </body>
</html>